### ISSUE TITLE
SkyPro Review

### ISSUE THREAD

**Issue by painassasin** [ipotemkin/messenger_fabrique#1]
1. зачем ты используешь обе библиотеки для чтения env (dotenv, environ)?
2. Debug стоит вынести в .env
3.  class UserRoles - ему явно не место в settings.py. Думаю его лучше положить в managers.py
4. Permission IsAdmin - оно зачем? В DRF есть втроенный IsAdminUser
5. команда на запуск Djnago указана и в  Dockerfile и в docker-compose, может стоит оставить только одну?
6. docker-compose 
6.1 отдельный сервис для миграций - а он вообще нужен? не проще делать миграции при запуске api? 
6.2 makemigrations точно делать не нужно, все миграции должны создаваться разработчиком, а не автоматически
6.3 сервис postgres - ты сначала пишешь DB_NAME  в env, а потом в healthcheck его палишь - как то не "секурно" получается

**Comment by ipotemkin** [comment]
Спасибо! Все поправил
